import { Capacitor } from '@capacitor/core'
import { PushNotifications } from '@capacitor/push-notifications'
import { supabase } from './supabase'

// Push only exists inside the Android app. On the web these functions do nothing.
// The notification text is generated by the server and never contains message content.

const TOKEN_KEY = 'dt:pushtoken'
let started = false
let pendingChat: string | null = null
let opener: ((chatId: string) => void) | null = null

const store = {
  get: () => {
    try {
      return localStorage.getItem(TOKEN_KEY)
    } catch {
      return null
    }
  },
  set: (t: string | null) => {
    try {
      if (t) localStorage.setItem(TOKEN_KEY, t)
      else localStorage.removeItem(TOKEN_KEY)
    } catch {
      /* storage unavailable: token is simply re-registered next launch */
    }
  },
}

/** The UI registers here to be told when a notification was tapped. A tap that happened earlier is delivered immediately. */
export function onOpenChat(cb: (chatId: string) => void): () => void {
  opener = cb
  if (pendingChat) {
    cb(pendingChat)
    pendingChat = null
  }
  return () => {
    if (opener === cb) opener = null
  }
}

export async function startPush(): Promise<void> {
  if (!Capacitor.isNativePlatform() || started) return
  started = true
  try {
    await PushNotifications.addListener('registration', async ({ value }) => {
      store.set(value)
      await supabase.rpc('register_push_token', { p_token: value, p_platform: 'android' })
    })
    await PushNotifications.addListener('pushNotificationActionPerformed', ({ notification }) => {
      const chatId = (notification.data as { chatId?: string } | undefined)?.chatId
      if (!chatId) return
      if (opener) opener(chatId)
      else pendingChat = chatId
    })
    await PushNotifications.createChannel({ id: 'messages', name: 'Messages', description: 'New chat messages and secrets', importance: 4 })

    let perm = await PushNotifications.checkPermissions()
    if (perm.receive.startsWith('prompt')) perm = await PushNotifications.requestPermissions()
    if (perm.receive === 'granted') await PushNotifications.register()
  } catch {
    started = false // Firebase not configured in this build, or permission flow failed; try again next launch
  }
}

/** Call before signing out, while the session is still valid, so this device stops getting the account's pushes. */
export async function stopPush(): Promise<void> {
  const token = store.get()
  if (!token) return
  try {
    await supabase.rpc('unregister_push_token', { p_token: token })
  } catch {
    /* offline: the server drops the token the next time FCM reports it dead */
  }
  store.set(null)
}
